server:
  port: 8090

jdbc:
  driverClassName: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/test
  username: root
  password: root
hibernate:
  dialect: org.hibernate.dialect.MySQL8Dialect

swagger:
  api-key:
  app-info:
    name: REST API
    description: Test project.
    version: V1
    term-of-service-url: /
    license: License
    license-url: /
    contact:
      name: Yasin Talha AKMAN
      url:
      email: yasin_akman@hotmail.de

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
