server:
  port: 8090

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver

swagger:
  api-key:
  app-info:
    name: REST API
    description: Test project.
    version: V1
    term-of-service-url: /
    license: License
    license-url: /
    contact:
      name: Yasin Talha AKMAN
      url:
      email: yasin_akman@hotmail.de